### ISSUE TITLE
Only 2 meetings are showed in Magnet using sched instead of 3

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-adaptor-sched#1]
It was agreed that Sched app will show in Magnet the 3 next sessions scheduled in the same day.
Doing some tests with London sched, and checking Berkeley venue:

https://mozillalondonallhands2016.sched.org/venue/Berkeley/Metropole+East+Tower

you can see that there are 4 meetings scheduled on June 14th but only 2 meetings are shown and should be 3:

https://tengam.org/adaptors/sched/?url=https://mozillalondonallhands2016.sched.org/venue/Berkeley/Metropole+East+Tower and selecting oembed option

**Comment by arcturus** [comment]
Closed by #7
