### ISSUE TITLE
Past events are shown

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-adaptor-sched#15]
If there is an sched with past events for a room, those are shown, instead of taking the new events coming.
Please see this example of an sched with past events:
https://ptyear2orientation2015.sched.org/venue/Delhi+Community+Center
There are events on 16th, 19th and 26th of May

Here you can see that the event shown is the one on May 16th instead of the coming event on May 26th:
https://tengam.org/adaptors/sched/?url=https://ptyear2orientation2015.sched.org/venue/Delhi+Community+Center
<img width="590" alt="captura de pantalla 2016-05-21 a las 20 53 49" src="https://cloud.githubusercontent.com/assets/1897507/15452089/35335978-1f96-11e6-9b89-6028dba0e52f.png">

**Comment by isabelrios** [comment]
Something similar happens for events happening in the same venue.
Here is a venue with several events on the day: 
https://communitydevelopmentextensi2016.sched.org/venue/Grandview+Ballroom

Only the first three are shown, no matter what time you check the app.
@wilsonpage  Both issues described here seems to be related to the fact that past events are shown but if the cause is different and a new patch is needed I can open a separate bug for this.
Thanks!

**Comment by isabelrios** [comment]
Something similar happens for events happening in the same venue on the same day.
Here is a venue with several events on the day: 
https://communitydevelopmentextensi2016.sched.org/venue/Grandview+Ballroom

Only the first three are shown, no matter what time you check the app.
@wilsonpage  Both issues described here seems to be related to the fact that past events are shown but if the cause is different and a new patch is needed I can open a separate bug for this.
Thanks!

**Comment by wilsonpage** [comment]
> Something similar happens for events happening in the same venue on the same day.

Are you talking about overlapping session in the same 'venue'? From [the link](https://communitydevelopmentextensi2016.sched.org/venue/Grandview+Ballroom) you posted, I can't see any overlapping.

Can you post a screenshot of what you're seeing?

**Comment by isabelrios** [comment]
@wilsonpage  Sorry I did not explain myself clearly enough, this is an screenshot of what we see:
![screenshot_2016-05-24-11-40-30](https://cloud.githubusercontent.com/assets/1897507/15499593/53470570-21a5-11e6-9ef3-1df238e174c0.png)

What I meant is that although there are more events in the day, you always see the first three, not the other.
If I understand it correctly, once one event is over, the next one should appear and so to cover all the events in that day for that venue.

**Comment by wilsonpage** [comment]
@isabelrios that is correct, we should be showing only the next three events. If an event is in progress, we should show it and the next 2.

Currently we're rendering serverside, which it means we don't have access to the client/device local time. I think a sensible solution would be to pass the raw JSON data and render events on the client based on local time. This means we can update the list the events as time elapses to prevent stale content.

**Comment by oteo** [comment]
@wilsonpage @arcturus Yeah we should go ahead with that solution and show an updated schedule (not showing past events) 
In case if it's a tricky solution or you don't have time to implement it before London All Hands we should, at least, show all the events/sessions scheduled during that day (be aware that there could be more than 3 events to be shown)

**Comment by arcturus** [comment]
Closed by #22
