### ISSUE TITLE
Problems with events date

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-adaptor-sched#2]
Using the same example than in issue #1
checking Berkeley venue in sched, the first sessions start on Tuesday June **14th**:

https://mozillalondonallhands2016.sched.org/venue/Berkeley/Metropole+East+Tower

but in Magnet app the date shown for those first events is Tuesday June **13th**, so the day is incorrect:

https://tengam.org/adaptors/sched/?url=https://mozillalondonallhands2016.sched.org/venue/Berkeley/Metropole+East+Tower and selecting oembed option

**Comment by isabelrios** [comment]
In case it is helpful, here is another example:
**Today May 12**, the event is **The Blind Spots**
https://dosavannahcalendar.sched.org/venue/Barrelhouse+South/125+W.+Congress+St.

But in Magnet, the date and event shown is the **Thursday May 4th, Polyrhythmics**:
https://tengam.org/adaptors/sched/?url=https://dosavannahcalendar.sched.org/venue/Barrelhouse+South/125+W.+Congress+St. and going to Check embed link

**Comment by isabelrios** [comment]
Execpt for my previous comment, what I am observing in the tests I am doing taking different rooms with different dates and times, is that the app always shows one day before of the date of the meeting.
Seems a general problem. So far I did not get the correct date for the room and date selected.

**Comment by arcturus** [comment]
Fixed by #10
