### ISSUE TITLE
Empty event for a venue

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-adaptor-sched#20]
This is the first time I see this issue, it does not happen with london all hands venues, but worth investigating in case we can see that in the future:

This is the sched url: https://ijas2016toronto.sched.org/venue/ILC+Room+100/Ryerson+University%E2%80%99s+International+Learning+Center+%28ILC%29%2C+240+Jarvis+Street%2C+Toronto

The converted url: https://tengam.org/adaptors/sched/?url=https://ijas2016toronto.sched.org/venue/ILC+Room+100/Ryerson+University%E2%80%99s+International+Learning+Center+%28ILC%29%2C+240+Jarvis+Street%2C+Toronto

And what is shown:
![captura de pantalla 2016-06-02 a las 11 00 24](https://cloud.githubusercontent.com/assets/1897507/15739680/6ea015b0-28b1-11e6-9cba-18d63311fe87.png)

**Comment by isabelrios** [comment]
In case it is useful, another example of this error:
Sched url: https://aalheconference2016.sched.org/venue/Kennedy%2FRoosevelt
Changed url: https://tengam.org/adaptors/sched/?url=https://aalheconference2016.sched.org/venue/Kennedy%2FRoosevelt

**Comment by arcturus** [comment]
@isabelrios unfortunately those events already passed, cannot check if this continues happening or not.

**Comment by isabelrios** [comment]
@arcturus Yeah, I will comment here with more examples in case I see it again. Thanks!

**Comment by isabelrios** [comment]
Will close this since it has not been reproducible again.
Feel free to open it if a new example comes up
