### ISSUE TITLE
The tile is not loaded - Error: Cannot read property 'status' of undefined in some venues

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-adaptor-sched#21]
Not happening with the venues we have for London, but it does not look good.
This is the sched url:
https://internationalassociationofu2016.sched.org/venue/CHEB+-+C264/5793+University+Ave

And the url changed:
https://tengam.org/adaptors/sched/?url=https://internationalassociationofu2016.sched.org/venue/CHEB+-+C264/5793+University+Ave
Here in Check embed, the tile is shown fine but it is not properly loaded in the android app:

![screenshot_2016-06-05-10-21-25](https://cloud.githubusercontent.com/assets/1897507/15816172/e238aabe-2bd1-11e6-8b35-1d4b5628bc18.png)

**Comment by arcturus** [comment]
@isabelrios can you try with the new deployed magnet adaptor?

**Comment by isabelrios** [comment]
@arcturus I can still see this error :(

**Comment by isabelrios** [comment]
Cannot reproduce this issue with that url anymore.
Closing it.

**Comment by isabelrios** [comment]
And this error is shown again :(
This is the sched url: https://lasvegasfilmfestival2016.sched.org/venue/Brenden+Theater%2C+Palms+Casino+/4321+W+Flamingo+Rd%2C+Las+Vegas%2C+NV+89103

and the tengam url: https://tengam.org/adaptors/sched/?url=https://lasvegasfilmfestival2016.sched.org/venue/Brenden+Theater%2C+Palms+Casino+/4321+W+Flamingo+Rd%2C+Las+Vegas%2C+NV+89103

As it happened before, not affecting london venues, and only seen on the android app, not in the tengam url

**Comment by isabelrios** [comment]
Downgrading the priority for now since our venues are not affected
