### ISSUE TITLE
Regression - Events for a venue are not shown

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-adaptor-sched#24]
With the latest nightly build and latest adaptor-sched, this is what is shown:
![screenshot_2016-06-05-22-09-52](https://cloud.githubusercontent.com/assets/1897507/15836265/430565a0-2c34-11e6-9f92-d7222e496cbe.png)

**Comment by arcturus** [comment]
This is really weird, when I visit with the browser:

https://tengam.org/adaptors/sched/?url=https%3A%2F%2Fmozillalondonallhands2016.sched.org%2Fvenue%2FMac%2BIver%2FPaddington

Seems ok to me, but when following the url, via sched or tengam I see the error

**Comment by arcturus** [comment]
Seems we could be hitting an error by extremely long url :S ... as we are sending all the information now for pages with too much information it may no work on our webviews

**Comment by isabelrios** [comment]
This is now fixed.
Events are shown again. There are a few things though that seems to be related to the latest patch, will open the issues
