### ISSUE TITLE
Regression - Time for the events is not correct

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-adaptor-sched#27]
For example for this venue:
https://mozillalondonallhands2016.sched.org/venue/Mac+Iver/Paddington

This is what is shown:
![captura de pantalla 2016-06-07 a las 18 24 32](https://cloud.githubusercontent.com/assets/1897507/15865937/03ade72a-2cdd-11e6-823e-8746c1e4b43e.png)

**Comment by arcturus** [comment]
Closed by #26
