### ISSUE TITLE
More than 5 events shown for a room

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-adaptor-sched#28]
Now the limit is to show maximum 5 events for a venue.
Here an example in which you can see 6:
Sched url: https://internationalassociationofu2016.sched.org/venue/CHEB+-+C140/5793+University+Ave
Tengam url: https://tengam.org/adaptors/sched/?url=https://internationalassociationofu2016.sched.org/venue/CHEB+-+C140/5793+University+Ave
![captura de pantalla 2016-06-07 a las 18 59 10](https://cloud.githubusercontent.com/assets/1897507/15867138/0469c6f2-2ce2-11e6-86f9-62dbe8a5da55.png)

**Comment by arcturus** [comment]
Closed by #26

**Comment by isabelrios** [comment]
Reopening, still 6 events are shown for a venue, not sure if this is a particular case due to that all the events are at the same time...
sched url: https://aalheconference2016.sched.org/venue/Imperial+Ballroom 
See Wednesday 8th

The tengam ulr is having the issue reported in #29 
https://tengam.org/adaptors/sched/?url=https://aalheconference2016.sched.org/venue/Imperial+Ballroom

**Comment by isabelrios** [comment]
This is weird, I was able to see the events, 6, as in previous comment, but now they do not appear for this venue as commented for the tengam url, it says No session.
Closing again till having other failing example

**Comment by isabelrios** [comment]
Not critial, but still seeing more than 5 events for venue:
sched url: https://2016teachapalooza.sched.org/venue/Barnes
tengam url: https://tengam.org/adaptors/sched/?url=https://2016teachapalooza.sched.org/venue/Barnes
![captura de pantalla 2016-06-09 a las 17 18 43](https://cloud.githubusercontent.com/assets/1897507/15935082/5f410948-2e66-11e6-8ab2-e100f95517af.png)
Downgrading the priority since our venues are not affected
