### ISSUE TITLE
Urls not found when there are special chars

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-adaptor-sched#3]
This URL
Checking this url in sched: 
https://dosavannahcalendar.sched.org/venue/Bayou+Café/144+N.+Abercorn+St.

And having the modified url
https://tengam.org/adaptors/sched/?url=https://dosavannahcalendar.sched.org/venue/Bayou+Café/144+N.+Abercorn+St.

Gives an error: 
**No Sched Venue URL found**
Please use this site: http://tengam.org/?url=https://dosavannahcalendar.sched.org/venue/Bayou+Caf%C3%A9/144+N.+Abercorn+St.?url=<sched venue url>

Other examples:
https://dosavannahcalendar.sched.org/venues/
Go to: Billy's Place room
https://dosavannahcalendar.sched.org/venue/Billy%E2%80%99s+Place/20+E.+Perry+St.%2C+second+floor

And convering it: 
https://tengam.org/adaptors/sched/?url=https://dosavannahcalendar.sched.org/venue/Billy%E2%80%99s+Place/20+E.+Perry+St.%2C+second+floor

Gives: No Sched Venue URL found
Please use this site: http://tengam.org/?url=https://dosavannahcalendar.sched.org/venue/Billy%E2%80%99s+Place/20+E.+Perry+St.%2C+second+floor?url=<sched venue url>

**Comment by isabelrios** [comment]
Hi @wilsonpage @arcturus I am still able to reproduce this issue, could I be missing something or converting the url in a wrong way?

Thanks!

**Comment by wilsonpage** [comment]
@isabelrios which URL are you testing? And how are you testing it?

**Comment by isabelrios** [comment]
Hi, this is one of the examples I am trying:

Checking this url in sched:
https://dosavannahcalendar.sched.org/venue/Bayou+Café/144+N.+Abercorn+St.

And having the modified url
https://tengam.org/adaptors/sched/?url=https://dosavannahcalendar.sched.org/venue/Bayou+Café/144+N.+Abercorn+St.

**Comment by wilsonpage** [comment]
@isabelrios ok, let me take a second look.

**Comment by isabelrios** [comment]
@wilsonpage thanks!

**Comment by wilsonpage** [comment]
@isabelrios should be working now. Although I'm a bit confused as there seems to be an issue with the 'Bayou Cafe' link schedule being empty. If I copy the URL out of the URL bar and paste it into Github comments and click it, it shows not items. If I paste the URL directly into the URL bar it works 😕 

https://dosavannahcalendar.sched.org/venue/Bayou%20Caf%C3%A9/144+N.+Abercorn+St.

**Comment by isabelrios** [comment]
@wilsonpage yeah, it is working now, thanks!
Agree, there is something weird with that url, have not found similar behaviour (now that the issue is closed) with others
