### ISSUE TITLE
Opening meetings details does not work correctly

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-adaptor-sched#4]
I tried with this:
https://mozillalondonallhands2016.sched.org/venue/Monarch+Suite/Metropole+West+Wing
Being modified as:
https://tengam.org/adaptors/sched/?url=https://mozillalondonallhands2016.sched.org/venue/Monarch+Suite/Metropole+West+Wing
Here if I click on embed and then on the event I can see its details: 
https://mozillalondonallhands2016.sched.org/event/72lY/london-all-hands-welcome-reception

From the app, I tap on the event name 
1- Nothing seems to happen(the link is not selected nor the background text changes),

2- Sometimes tapping on the event name several times and afer a while a page is shown but cannot be open to interact with it
![openeventdetails](https://cloud.githubusercontent.com/assets/1897507/15254306/6e2266fe-1936-11e6-94f7-481bc2bf3f2e.png)

**Comment by isabelrios** [comment]
With latest build, opening the link from the tile details works. 
But, would like to confirm if the link shown is correct as the experience is different than on the web site.
For example with this venue:
https://mozillalondonallhands2016.sched.org/venue/Monarch+Suite/Metropole+West+Wing

Converted as:
https://tengam.org/adaptors/sched/?url=https://mozillalondonallhands2016.sched.org/venue/Monarch+Suite/Metropole+West+Wing

If you click on the event 'London All Hands Welcome Reception'
On the web you see this: 
https://mozillalondonallhands2016.sched.org/event/72lY/london-all-hands-welcome-reception

And from the app:
First view:
![event details 1](https://cloud.githubusercontent.com/assets/1897507/15535744/f21d5e8c-226e-11e6-8f43-bd7fd629be45.png)

Then if you tap on Schedule, you see more events, not the details of the event from which the link was launched:
![event details 2](https://cloud.githubusercontent.com/assets/1897507/15535758/01e03312-226f-11e6-9d4c-d94d787d7205.png)

And finally if you tap again on the event name 'London All Hands Welcome Reception' (in the previous screenshot is now shown but is below the latest event name), you can see its details as shown in the web site:
![event details 3](https://cloud.githubusercontent.com/assets/1897507/15535777/1ac9b2ae-226f-11e6-83b7-0abe55bbbc18.png)

Also, if you click on Speakers, a blank page is shown:
![event details speakers](https://cloud.githubusercontent.com/assets/1897507/15535785/28b8cd28-226f-11e6-9904-4caff170d55e.png)

**Comment by isabelrios** [comment]
With latest commit ([aa45a02](https://github.com/mozilla-magnet/magnet-client/commit/aa45a026e2c3c4396045f62ec671eaf13cf2a2c9)) this issue is more evident again. It is not easy to tap on the event name and get the browser open. You have to tap several times and not always is open.

**Comment by wilsonpage** [comment]
So I think the blank Sched page is a bug in Sched when loading a desktop URL into a mobile client.

From where I see it we have two options:
1. We navigate all clicks to the 'Venue' page and not the specific event (simple)
2. We transform desktop session URLs into mobile session URLs to avoid broken redirect (more complex, could break)

I thought about the idea of scraping the mobile site instead of the desktop, but it seems the mobile site is rendered clientside. I did notice that the API key is included in the initial payload, so we could have the option of extracting that, and using the JSON API unofficially; although this is a little naughty.

**Comment by wilsonpage** [comment]
If we favour Option 2 we just need to make sure that we have the session id to hand. The mobile session URLs look as follows:

https://mozillalondonallhands2016.sched.org/mobile/#session:58a086aa3b7369e810e5f4c19f14d6ae

**Comment by wilsonpage** [comment]
@arcturus is this fixed?

**Comment by arcturus** [comment]
Yes this has been hot fixed yesterday.
