### ISSUE TITLE
Confirm it shows the most relevant day/times

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-adaptor-sched#6]
We need to make sure that events in a past are never shown and that events that are shown are the next ones to happen.

**Comment by arcturus** [comment]
Perhaps @isabelrios could give us a hand here.

We can track events happening on sched right now, there are a bunch in their web page.

**Comment by isabelrios** [comment]
Hi, 
Yes, I have already started to look at this, will continue next week. 
 The idea is to define some tests to cover all the posible scenarios and run them to be sure we are showing everything fine in sched in regards to dates (bug open[ issue #2](https://github.com/mozilla-magnet/magnet-adaptor-sched/issues/2)) and the info presented (bugs open issue [#1](https://github.com/mozilla-magnet/magnet-adaptor-sched/issues/1) and [#4](https://github.com/mozilla-magnet/magnet-adaptor-sched/issues/4))
